# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - libsndfile1
  tools:
    python: "3.13"
  jobs:
    install:
      - python -m pip install --no-cache dir "pip >= 25.1"
      - python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir --group doc .

sphinx:
   configuration: doc/conf.py
